### ISSUE TITLE
Gather previous attendee quotes for ticket call-to-action.

### ISSUE THREAD

**Issue by joshmobley** [joshmobley/hopscotch2017#28]

**Comment by joshmobley** [comment]
I believe the plan is to have a handful of these so that they're different on each page. Minimum for launch I'd think we need 3. Ideally, 5+. It looks like this:

![image](https://cloud.githubusercontent.com/assets/933565/25317124/5d9df194-2840-11e7-83ad-ae8399b038da.png)

**Comment by chrissim15** [comment]
Working on these now. I'll get 5 prepped and we can choose which we want to use.
